# Generated by Django 5.1.2 on 2025-05-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assestapp', '0002_alter_details_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(default=True, max_length=10, null=True),
        ),
    ]
