# Generated by Django 5.1.2 on 2025-05-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assestapp', '0003_employee_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Status',
            field=models.CharField(default='Inactive', max_length=8, null=True),
        ),
    ]
