# Generated by Django 5.1.2 on 2025-05-30 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assestapp', '0004_employee_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Status',
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(default='Inactive', max_length=8),
        ),
    ]
