# Generated by Django 5.1.2 on 2025-06-02 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assestapp', '0005_remove_employee_status_employee_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='features',
            new_name='description',
        ),
        migrations.AddField(
            model_name='details',
            name='units',
            field=models.CharField(default='numbers', max_length=50),
        ),
    ]
