# Generated by Django 5.1.2 on 2025-06-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assestapp', '0006_rename_features_details_description_details_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigned',
            name='date',
            field=models.DateField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='date',
            field=models.DateField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date',
            field=models.DateField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(default='Active', max_length=8),
        ),
    ]
