# Generated by Django 5.1.2 on 2025-06-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assestapp', '0007_alter_assigned_date_alter_details_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigned',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
