# Generated by Django 5.1.2 on 2025-06-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assestapp', '0008_alter_assigned_date_alter_details_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigned',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
