# Generated by Django 5.1.2 on 2025-06-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assestapp', '0009_alter_assigned_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
