# Generated by Django 5.1.2 on 2025-06-04 11:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assestapp', '0010_alter_employee_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAssigned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('modelno', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('units', models.CharField(max_length=100)),
                ('assigned_date', models.DateField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assestapp.employee')),
            ],
        ),
    ]
